spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drone-zone-db
    username: root
    password: dronezone
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

open-aip:
  url: https://api.core.openaip.net/api